name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Run apt
      run: sudo apt update && sudo apt install -yq inkscape imagemagick

    - name: Make images
      run: make images

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Type check
      run: npm run type

    - name: Test
      run: npm test

    - name: Build
      run: npm run build

    - name: Make chrome extension zip
      run: make chrome
